[Log]
Level = 'debug'

[WebServer]
AllowOrigins = '\*'
SecureCookies = false

[WebServer.TLS]
HTTPSPort = 0

[[EVM]]
ChainID = '31337'
NoNewHeadsThreshold = '60000m0s'

[[EVM.Nodes]]
Name = 'Hardhat'
WSURL = 'ws://hardhat:8545'
HTTPURL = 'http://hardhat:8545'

