FROM --platform=$BUILDPLATFORM node:20-alpine

WORKDIR /chainlink

# Install system dependencies
RUN apk add --no-cache bash postgresql-client

# Copy required files
COPY . .

EXPOSE 6688

ENTRYPOINT ["chainlink"]